### ISSUE TITLE
KeyError: '__inner__'

### ISSUE THREAD

**Issue by haferje** [julvo/reloading#8]
I'm trying to use the `@reloading` decorator, and am receiving the following error:
```
.local/lib/python3.8/site-packages/reloading/reloading.py", line 182, in wrapped
    inner = caller_locals[fn.__name__].__dict__['__inner__']
KeyError: '__inner__'
```
I can get the loop version working but not the decorator version.  My code is fairly simple and all contained in a single file.
Am I doing something wrong? I am using Python 3.8.2

**Comment by haferje** [comment]
Did you mean for line 182 to be `inner = wrapped.__dict__['__inner__']`? This change seems to work for me.

**Comment by julvo** [comment]
Hey @haferje, thanks for opening this issue and also opening the PR with a fix! Do you happen to know what changed between Python 3.6 to 3.8 that causes this issue? Up to 3.6 `@reloading` works, but on 3.8 it doesn't.

I couldn't find anything about a change of `exec` in the docs so far but am curious to get to the bottom of this before merging to be sure I understand what's going on and avoid unwanted side effects.

**Comment by haferje** [comment]
Honestly, I'm not sure either, but the online documentation does note 

> Pass an explicit _locals_ dictionary if you need to see effects of the code on _locals_ after function exec() returns.

so when you pass `caller_locals` to `exec()`, the function reference is overwritten, and the key `__inner__` no longer exists.  This comment is the same in the documentation for v3.6, so I can't be sure anything has changed.  Copying the variables before redefining the method allows it to be done in a temporary variable so the original `__inner__` property remains intact, but is updated to point to the reloaded function reference.  

I was trying to imitate your test code `TEST_CHANGING_SOURCE_FN_CONTENT`, but it wasn't working for me, and I noticed the decorated reloading method was being called from a loop, which itself was reloaded (and capturing the exception), so I believe the test might have been giving you false positives?

You have written a crafty method for reloading code and I'm trying to understand it.  However, it's a smaller part of a larger project I'm focusing on and my python experience isn't as advanced, so I'm uncertain the PR is optimal, but it keeps my project moving forward :smiley: 

Thank you!

**Comment by julvo** [comment]
Thanks for expanding on this. Now had the time to test more on different versions and think I found what's causing the issue.

> so when you pass caller_locals to exec(), the function reference is overwritten, and the key __inner__ no longer exists.

This is intended - how it works is that the function definition is executed in the caller's scope including the reloading decorator, so the function is reloaded from source, wrapped again and `__inner__` is set.

The error seems to be caused by a behaviour change of `ast.parse` from 3.7 to 3.8 which I couldn't find in the docs. Up to 3.7, the decorators where included in the line number of the function definition, whereas  with 3.8, the function definition starts after the decorators. Hence, when locating and executing the function definition in 3.8, the `@reloading` decorator is not included and, therefore, `__inner__` is not set (as `__inner__` is set in the decorator function, not the inner function).

I think I have a fix which I'll push soon. Without having run your fork, I suspect manually copying the inner function into the caller's locals won't work, as afterwards the function is not wrapped in `@reloading` anymore and won't reload again after the first reloading from source.

**Comment by haferje** [comment]
Thank you for clarifying the code.  I understood executing in the caller's scope, but what wasn't making sense to me was the purpose for the `__inner__` property, as your code comment (as we now know) wasn't applicable in v3.8:
```
# the newly defined function will also be decorated 
# with `reloading` and, hence, we call the inner function without
# triggering another reload (and another one...)
```
Yes, I suspect my PR wasn't complete and may not work for everyone.  Documentation suggests you don't modify locals directly, but my case was simple and it works for what I currently need.

You may still want to update your test case which I mentioned, as it looked to be obscuring the very error I was getting.

Thank you for your timely response!
